name: "build-android"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-22.04
    steps:
      # 拉取仓库代码
      - uses: actions/checkout@v3

      - name: build
        working-directory: ~/
        run: sudo -S chmod +x ./build-android.sh ; sudo -S ./build-android.sh
