name: "build-armbian"
on:
  schedule:
    - cron: '0 17 * * *'
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_build_type:
        descriptions: "build type nightly/stable"
        required: false
        default: "nightly"
        type: choice
        options:
          - nightly
          - stable
      set_release:
        description: "Select OS Release."
        required: false
        default: "jammy"
        type: choice
        options:
          - jammy
          - noble
          - bullseye
          - bookworm
      set_target:
        description: "Select build target."
        required: false
        default: "build"
        type: choice
        options:
          - build
          - kernel
      set_ui:
        description: "Select ui."
        required: false
        default: "xfce"
        type: choice
        options:
          - minimal
          - server
          - xfce
          - gnome
      set_kernel_branch:
        description: "Select kernel branch."
        required: false
        default: "current"
        type: choice
        options:
          - current
          - edge
      set_armbian_branch:
        description: "Select Armbian branch."
        required: false

      set_armbian_version:
        description: "Set different version"
        required: false

      set_armbian_version_suffix:
        description: "Set version suffix"
        required: false
        default: "-robin"

jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: robinZhao/tpm312-build@main
        with:
          armbian_token: "${{secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release: "${{inputs.set_release}}"                        # userspace
          armbian_target: "${{inputs.set_target}}"                        # build=image, kernel=kernel
          armbian_board: "tpm312"                   # build target
          armbian_ui: "${{inputs.set_ui}}"
          armbian_kernel_branch: "${{inputs.set_kernel_branch}}"
          armbian_branch: "${{inputs.set_armbian_branch}}"
          armbian_version: "${{inputs.set_armbian_version}}"
          armbian_version_suffix: "${{inputs.set_armbian_version_suffix}}"
          build_type: "${{inputs.set_build_type}}"
