name: "build-uboot"
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:



env:
  TZ: Asia/Shanghai
  PREFER_DOCKER: no
jobs:
  build-armbian:
    runs-on: ubuntu-22.04
    steps:
      - uses: robinZhao/tpm312-build@main
        with:
          armbian_token: "${{secrets.GITHUB_TOKEN }}"  # GitHub token               # userspace
          armbian_target: "uboot"                        # build=image, kernel=kernel
          armbian_board: "tpm312"                   # build target
          build_type: "stable"
          armbian_branch: "main"
          armbian_artifacts: "build/output/debs/"
